//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestAppMetro {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Json {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Json() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestAppMetro.Json", typeof(Json).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;SEM:12&quot;,
        ///    &quot;shortName&quot;: &quot;12&quot;,
        ///    &quot;longName&quot;: &quot;Eybens Maisons Neuves / Saint-Martin-d&apos;Hères Les Alloves&quot;,
        ///    &quot;color&quot;: &quot;009930&quot;,
        ///    &quot;textColor&quot;: &quot;FFFFFF&quot;,
        ///    &quot;mode&quot;: &quot;BUS&quot;,
        ///    &quot;type&quot;: &quot;PROXIMO&quot;
        ///  }
        ///].
        /// </summary>
        internal static string json12 {
            get {
                return ResourceManager.GetString("json12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;SEM:13&quot;,
        ///    &quot;shortName&quot;: &quot;13&quot;,
        ///    &quot;longName&quot;: &quot;Meylan Lycée du Grésivaudan / Poisat Prémol&quot;,
        ///    &quot;color&quot;: &quot;00BC9E&quot;,
        ///    &quot;textColor&quot;: &quot;FFFFFF&quot;,
        ///    &quot;mode&quot;: &quot;BUS&quot;,
        ///    &quot;type&quot;: &quot;PROXIMO&quot;
        ///  }
        ///].
        /// </summary>
        internal static string json13 {
            get {
                return ResourceManager.GetString("json13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;SEM:16&quot;,
        ///    &quot;shortName&quot;: &quot;16&quot;,
        ///    &quot;longName&quot;: &quot;MEYLAN Lycée du Grésivaudan / CORENC Montfleury / PONT-DE-CLAIX Gendarmerie&quot;,
        ///    &quot;color&quot;: &quot;739ECC&quot;,
        ///    &quot;textColor&quot;: &quot;FFFFFF&quot;,
        ///    &quot;mode&quot;: &quot;BUS&quot;,
        ///    &quot;type&quot;: &quot;PROXIMO&quot;
        ///  }
        ///].
        /// </summary>
        internal static string json16 {
            get {
                return ResourceManager.GetString("json16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;SEM:57&quot;,
        ///    &quot;shortName&quot;: &quot;57&quot;,
        ///    &quot;longName&quot;: &quot;GRENOBLE Victor Hugo / ST ISMIER Bois Français&quot;,
        ///    &quot;color&quot;: &quot;522E91&quot;,
        ///    &quot;textColor&quot;: &quot;FFFFFF&quot;,
        ///    &quot;mode&quot;: &quot;BUS&quot;,
        ///    &quot;type&quot;: &quot;FLEXO&quot;
        ///  }
        ///].
        /// </summary>
        internal static string json57 {
            get {
                return ResourceManager.GetString("json57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;C38:6060&quot;,
        ///    &quot;shortName&quot;: &quot;6060&quot;,
        ///    &quot;longName&quot;: &quot;CHAMBERY-CHAPAREILLAN-GRENOBLE&quot;,
        ///    &quot;color&quot;: &quot;FCCD51&quot;,
        ///    &quot;textColor&quot;: &quot;000000&quot;,
        ///    &quot;mode&quot;: &quot;BUS&quot;,
        ///    &quot;type&quot;: &quot;C38&quot;
        ///  }
        ///].
        /// </summary>
        internal static string json6060 {
            get {
                return ResourceManager.GetString("json6060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;C38:6200&quot;,
        ///    &quot;shortName&quot;: &quot;6200&quot;,
        ///    &quot;longName&quot;: &quot;ALLEVARD-GRENOBLE&quot;,
        ///    &quot;color&quot;: &quot;FCCD51&quot;,
        ///    &quot;textColor&quot;: &quot;000000&quot;,
        ///    &quot;mode&quot;: &quot;BUS&quot;,
        ///    &quot;type&quot;: &quot;C38&quot;
        ///  }
        ///].
        /// </summary>
        internal static string json6200 {
            get {
                return ResourceManager.GetString("json6200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;SEM:C1&quot;,
        ///    &quot;shortName&quot;: &quot;C1&quot;,
        ///    &quot;longName&quot;: &quot;GRENOBLE Cité Jean Macé / MEYLAN Maupertuis&quot;,
        ///    &quot;color&quot;: &quot;FFE000&quot;,
        ///    &quot;textColor&quot;: &quot;000000&quot;,
        ///    &quot;mode&quot;: &quot;BUS&quot;,
        ///    &quot;type&quot;: &quot;CHRONO&quot;
        ///  }
        ///].
        /// </summary>
        internal static string jsonC1 {
            get {
                return ResourceManager.GetString("jsonC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;SEM:C4&quot;,
        ///    &quot;shortName&quot;: &quot;C4&quot;,
        ///    &quot;longName&quot;: &quot;Grenoble Victor Hugo / Eybens Le Verderet&quot;,
        ///    &quot;color&quot;: &quot;FFC900&quot;,
        ///    &quot;textColor&quot;: &quot;000000&quot;,
        ///    &quot;mode&quot;: &quot;BUS&quot;,
        ///    &quot;type&quot;: &quot;CHRONO&quot;
        ///  }
        ///].
        /// </summary>
        internal static string jsonC4 {
            get {
                return ResourceManager.GetString("jsonC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;C38:EXP1&quot;,
        ///    &quot;shortName&quot;: &quot;EXP1&quot;,
        ///    &quot;longName&quot;: &quot;EXPRESS VOIRON-GRENOBLE-CROLLES (EXP-1)&quot;,
        ///    &quot;color&quot;: &quot;FCCD51&quot;,
        ///    &quot;textColor&quot;: &quot;000000&quot;,
        ///    &quot;mode&quot;: &quot;BUS&quot;,
        ///    &quot;type&quot;: &quot;C38&quot;
        ///  }
        ///].
        /// </summary>
        internal static string jsonEXP1 {
            get {
                return ResourceManager.GetString("jsonEXP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;C38:EXP2&quot;,
        ///    &quot;shortName&quot;: &quot;EXP2&quot;,
        ///    &quot;longName&quot;: &quot;EXPRESS CHAMP PRES FROGES-VOREPPE (EXP-2)&quot;,
        ///    &quot;color&quot;: &quot;FCCD51&quot;,
        ///    &quot;textColor&quot;: &quot;000000&quot;,
        ///    &quot;mode&quot;: &quot;BUS&quot;,
        ///    &quot;type&quot;: &quot;C38&quot;
        ///  }
        ///].
        /// </summary>
        internal static string jsonEXP2 {
            get {
                return ResourceManager.GetString("jsonEXP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [
        ///  {
        ///    &quot;id&quot;: &quot;SEM:1986&quot;,
        ///    &quot;name&quot;: &quot;GRENOBLE, CASERNE DE BONNE&quot;,
        ///    &quot;lon&quot;: 5.72533,
        ///    &quot;lat&quot;: 45.18506,
        ///    &quot;lines&quot;: [
        ///      &quot;SEM:13&quot;,
        ///      &quot;SEM:16&quot;,
        ///      &quot;SEM:C4&quot;,
        ///      &quot;SEM:13&quot;,
        ///      &quot;SEM:16&quot;,
        ///      &quot;SEM:C4&quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;SEM:1987&quot;,
        ///    &quot;name&quot;: &quot;GRENOBLE, CASERNE DE BONNE&quot;,
        ///    &quot;lon&quot;: 5.72542,
        ///    &quot;lat&quot;: 45.18509,
        ///    &quot;lines&quot;: [
        ///      &quot;SEM:16&quot;,
        ///      &quot;SEM:16&quot;
        ///    ]
        ///  },
        ///  {
        ///    &quot;id&quot;: &quot;SEM:0753&quot;,
        ///    &quot;name&quot;: &quot;GRENOBLE, DOCTEUR MARTIN&quot;,
        ///    &quot;lon&quot;: 5.72686,        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string JsonNearYou {
            get {
                return ResourceManager.GetString("JsonNearYou", resourceCulture);
            }
        }
    }
}
